// This file contains the data for the dog groups that are used in the dog groups service
export const dogGroups = {
  dogSizeGroups: {
    small: [
      'Yorkshire Terrier',
      'Dachshund',
      'Pembroke Welsh Corgi',
      'Shih Tzu',
      'Miniature Schnauzer',
      'Boston Terrier',
      'Havanese',
      'Pug',
      'Chihuahua',
      'Maltese',
      'West Highland White Terrier',
      'Papillon',
      'Miniature American Shepherd',
      'Italian Greyhound',
      'Chinese Shar-Pei',
      'Cairn Terrier',
      'English Cocker Spaniel',
      'Pekingese',
      'Russell Terrier',
      'Toy Fox Terrier',
      'Norwegian Elkhound',
      'Jack Russell Terrier',
      'American Water Spaniel',
      'Australian Terrier',
      'Bedlington Terrier',
      'Belgian Tervuren',
      'Dandie Dinmont Terrier',
      'Poodle'
    ],
    medium: [
      'Bulldog',
      'Beagle',
      'French Bulldog',
      'Cocker Spaniel',
      'Brittany',
      'Basset Hound',
      'Border Collie',
      'Bichon Frise',
      'Australian Cattle Dog',
      'Scottish Terrier',
      'Portuguese Water Dog',
      'Airedale Terrier',
      'Dalmatian',
      'Soft Coated Wheaten Terrier',
      'Irish Setter',
      'Samoyed',
      'Bull Terrier',
      'Standard Schnauzer',
      'Staffordshire Bull Terrier',
      'American Cocker Spaniel',
      'Whippet',
      'Vizsla',
      'Bloodhound',
      'Basenji',
      'Fox Terrier',
      'Pointer',
      'Finnish Spitz',
      'Bracco Italiano',
      'Briard',
      'Cesky Terrier',
      'Clumber Spaniel',
      'Curly-Coated Retriever',
      'Flat-Coated Retriever',
      'Greyhound'
    ],
    large: [
      'Labrador Retriever',
      'German Shepherd',
      'Golden Retriever',
      'Rottweiler',
      'Boxer',
      'Siberian Husky',
      'Australian Shepherd',
      'Great Dane',
      'Doberman Pinscher',
      'Bernese Mountain Dog',
      'Shetland Sheepdog',
      'English Springer Spaniel',
      'Mastiff',
      'Cane Corso',
      'Collie',
      'Weimaraner',
      'Newfoundland',
      'Rhodesian Ridgeback',
      'Akita',
      'Belgian Malinois',
      'St. Bernard',
      'Bullmastiff',
      'Chow Chow',
      'German Shorthaired Pointer',
      'Alaskan Malamute',
      'Old English Sheepdog',
      'American Staffordshire Terrier',
      'Irish Wolfhound',
      'Afghan Hound',
      'Leonberger',
      'Neapolitan Mastiff',
      'Nova Scotia Duck Tolling Retriever',
      'Anatolian Shepherd Dog',
      'Black and Tan Coonhound',
      'Bluetick Coonhound',
      'Boykin Spaniel'
    ]
  },
  dogTemperamentGroups: {
    independent: ['Siberian Husky', 'Akita', 'Shiba Inu', 'Basenji', 'Afghan Hound', 'Saluki'],
    confident: [
      'German Shepherd',
      'Rottweiler',
      'Doberman Pinscher',
      'Boxer',
      'Bullmastiff',
      'Belgian Malinois'
    ],
    timid: [
      'Chihuahua',
      'Italian Greyhound',
      'Whippet',
      'Shih Tzu',
      'Cairn Terrier',
      'Norwegian Elkhound'
    ],
    laidback: [
      'Basset Hound',
      'Newfoundland',
      'Saint Bernard',
      'Bulldog',
      'Leonberger',
      'Clumber Spaniel'
    ],
    affectionate: [
      'Labrador Retriever',
      'Golden Retriever',
      'Cavalier King Charles Spaniel',
      'Pug',
      'French Bulldog',
      'Bichon Frise'
    ],
    adaptable: [
      'Poodle',
      'Border Collie',
      'Australian Shepherd',
      'Portuguese Water Dog',
      'American Cocker Spaniel',
      'Papillon'
    ]
  }
};
